import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How SparkLifeLab collects, uses, and protects your personal data.",
  robots: { index: false, follow: false },
};

export default function PrivacyPolicyPage() {
  return (
    <section className="section-pad" style={{ background: "var(--paper)" }}>
      <div className="container-narrow">
        <p className="kicker">Legal</p>
        <span aria-hidden className="section-divider" />
        <h1 className="display-section">Privacy Policy</h1>

        {/* TODO: Replace this placeholder with final Privacy Policy copy.
             Generate final copy using Termly (termly.io), iubenda, or a
             qualified lawyer. Ensure GDPR / DSGVO compliance for EU visitors.
             Do not invent company registration data, addresses, or contact
             details that have not been confirmed by the client. */}

        <div className="mt-10 rounded-sm border px-6 py-5 text-[0.88rem] text-[color:var(--mid-navy)]"
          style={{ borderColor: "var(--color-line)", background: "var(--cream)" }}>
          <p className="font-medium text-[color:var(--deep-navy)]">
            ⚠ Placeholder — final legal copy required
          </p>
          <p className="mt-1">
            This page is a placeholder. Final Privacy Policy copy must be
            generated by Termly, iubenda, or reviewed by a qualified lawyer
            before this site goes live.
          </p>
        </div>

        <div className="mt-10 space-y-8 text-[0.95rem] leading-relaxed text-[color:var(--mid-navy)]">
          <div>
            <h2 className="display-sub mb-3">What data we collect</h2>
            <p className="body-copy">
              When you use the Midlife Clarity Check or register interest in
              the SparkLife Identity Lab, we collect your name and email address
              so we can send you the requested materials and relevant
              communications.
            </p>
            <p className="body-copy">
              We do not collect sensitive personal data. We do not sell your
              data to third parties.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">How we use your data</h2>
            <p className="body-copy">
              Your name and email are used to deliver the Midlife Clarity Check
              and to keep you informed about SparkLifeLab programmes and
              updates. You can unsubscribe at any time using the link in any
              email we send.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Cookies</h2>
            <p className="body-copy">
              We use essential cookies required for the website to function.
              With your consent, we may also use analytics cookies to
              understand how visitors use the site. You can manage your
              preferences using the cookie banner.
            </p>
            <p className="body-copy">
              See our <Link href="/cookie-policy" className="underline underline-offset-2">Cookie Policy</Link> for
              more detail.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Your rights</h2>
            <p className="body-copy">
              You have the right to access, correct, or delete the personal
              data we hold about you. To exercise these rights, contact us
              at{" "}
              <a
                href="mailto:hello@spark-life-lab.com"
                className="underline underline-offset-2"
              >
                hello@spark-life-lab.com
              </a>
              .
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Contact</h2>
            <p className="body-copy">
              SparkLifeLab ·{" "}
              <a
                href="mailto:hello@spark-life-lab.com"
                className="underline underline-offset-2"
              >
                hello@spark-life-lab.com
              </a>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
