import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cookie Policy",
  description: "How SparkLifeLab uses cookies and similar technologies.",
  robots: { index: false, follow: false },
};

export default function CookiePolicyPage() {
  return (
    <section className="section-pad" style={{ background: "var(--paper)" }}>
      <div className="container-narrow">
        <p className="kicker">Legal</p>
        <span aria-hidden className="section-divider" />
        <h1 className="display-section">Cookie Policy</h1>

        {/* TODO: Replace with final Cookie Policy generated by Termly,
             iubenda, or equivalent before going live. Ensure GDPR / ePrivacy
             compliance for EU visitors. */}

        <div className="mt-10 rounded-sm border px-6 py-5 text-[0.88rem] text-[color:var(--mid-navy)]"
          style={{ borderColor: "var(--color-line)", background: "var(--cream)" }}>
          <p className="font-medium text-[color:var(--deep-navy)]">
            ⚠ Placeholder — final legal copy required
          </p>
          <p className="mt-1">
            This page is a placeholder. Final Cookie Policy must be generated
            by Termly, iubenda, or reviewed by a qualified lawyer before this
            site goes live.
          </p>
        </div>

        <div className="mt-10 space-y-8 text-[0.95rem] leading-relaxed text-[color:var(--mid-navy)]">
          <div>
            <h2 className="display-sub mb-3">What are cookies?</h2>
            <p className="body-copy">
              Cookies are small text files placed on your device when you visit
              a website. They help the website remember your preferences and
              understand how you interact with the site.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Essential cookies</h2>
            <p className="body-copy">
              Essential cookies are required for the website to function. They
              cannot be disabled. They include cookies that remember your
              cookie consent preference.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Analytics cookies</h2>
            <p className="body-copy">
              With your consent, we may use analytics cookies to understand how
              visitors interact with the site. These help us improve the
              experience for future visitors. No analytics cookies are set
              before you give consent.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Managing your preferences</h2>
            <p className="body-copy">
              You can review and update your cookie preferences at any time
              using the cookie banner, accessible via the &ldquo;Manage
              cookies&rdquo; link in the footer.
            </p>
          </div>

          <div>
            <h2 className="display-sub mb-3">Contact</h2>
            <p className="body-copy">
              Questions about cookies?{" "}
              <a
                href="mailto:hello@spark-life-lab.com"
                className="underline underline-offset-2"
              >
                hello@spark-life-lab.com
              </a>
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
